name: Code Coverage

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Set up Chrome
        uses: browser-actions/setup-chrome@latest

      - name: Install dependencies
        run: npm install

      - name: Run tests with coverage
        run: npm test -- --code-coverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
            CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          name: code-coverage
          path: coverage
